---
- name: "create vhost config: {{ vhost }}"
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf/sites-available/{{ vhost }}.{{ host }}
  notify:
    - reload apache

- name: create webroot
  file:
    path: "{{ root_path }}"
    state: directory
    owner: http
    group: "{{ dir_group }}"
    mode: u=rwx,g=rwxs,o=rx
  when: root_path is defined

- name: create webroot
  file:
    path: /srv/http/{{ root_dir }}
    state: directory
    owner: http
    group: "{{ dir_group }}"
    mode: u=rwx,g=rwxs,o=rx
  when: root_path is not defined

- name: request a certificate
  include_role:
    name: letsencrypt
  vars:
    domain: "{{ vhost }}.{{ host }}"

- name: "enable vhost: {{ vhost }}"
  command: a2ensite {{ vhost }}.{{ host }}
  args:
    creates: /etc/httpd/conf/sites-enabled/{{ vhost }}.{{ host }}
  notify:
    - reload apache
