---
- name: generate private key
  shell: openssl genrsa 4096 > /etc/ssl/{{ domain }}.key
  args:
    creates: /etc/ssl/{{ domain }}.key

- name: protect private key
  file:
    path: /etc/ssl/{{ domain }}.key
    group: ssl
    mode: u=rw,g=r,o-rwx

- name: add domain to domain list
  lineinfile:
    path: /etc/lets-encrypt/domains
    line: "{{ domain }} {{ ' '.join(aliases) }}"
    state: present
  notify:
    - request new certs
