---
- name: create znc user
  include_role:
    name: make_user
  vars:
    user: znc
    password: "{{ znc_user_pass }}"
    mail: "{{ admin_mail }}"
    ugroups:
      - ssl

- name: install znc dependencies
  pacman:
    pkg:
      - tcl
      - python
      - perl
      - cyrus-sasl
      - yajl
    state: present

- name: install gpg keys for aur packages
  become: yes
  become_user: aur_builder
  command: gpg --recv-keys {{ item }}
  with_items:
    - 487EACC08557AD082088DABA1EB2638FF56C0C53

- name: remove znc
  pacman:
    name: znc-git
    state: absent
  when: znc_force_rebuild|bool

- name: install znc
  become: yes
  become_user: aur_builder
  aur:
    name: znc-git

- name: make sure znc is stopped
  service:
    name: znc
    state: stopped

- name: configure znc
  become: yes
  become_user: znc
  template:
    src: znc.conf.j2
    dest: ~/.znc/configs/znc.conf

- name: request cert
  include_role:
    name: letsencrypt
  vars:
    domain: "{{ znc_host }}"

- name: register znc for reload on cert renewal
  lineinfile:
    path: /etc/lets-encrypt/services
    line: znc

- name: generate dhparams
  become: yes
  become_user: znc
  command: openssl dhparam -out ~/.znc/znc.pem 4096
  args:
    creates: ~/.znc/znc.pem

- name: start znc
  service:
    name: znc
    state: started
    enabled: yes
